# Minimal stub for plotly.graph_objects (streamlit_app uses Figure, Bar, Pie, update_layout).
from typing import Any

class Figure:
    def __init__(self, data: Any = ..., layout: Any = ..., *args: Any, **kwargs: Any) -> None: ...
    def update_layout(self, *args: Any, **kwargs: Any) -> Any: ...

class Bar:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Pie:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

def __getattr__(name: str) -> Any: ...
