-- Teardown Script: Remove all Snowfort WAF test objects
-- Companion to demo_setup.sql. Safe to run multiple times.

USE ROLE ACCOUNTADMIN;

-- Warehouses
DROP WAREHOUSE IF EXISTS BAD_COST_WH;
DROP WAREHOUSE IF EXISTS BAD_MC_WH;
DROP WAREHOUSE IF EXISTS SNOWFORT_TEST_PUBLIC_WH;

-- Databases (CASCADE drops all schemas/tables)
DROP DATABASE IF EXISTS BAD_PRACTICE_DB;
DROP DATABASE IF EXISTS PRD_BAD_DB;
DROP DATABASE IF EXISTS SNOWFORT_TEST_UNDOCUMENTED_DB;

-- Users
DROP USER IF EXISTS BAD_ADMIN_USER;
DROP USER IF EXISTS BAD_SVC_USER;
DROP USER IF EXISTS SNOWFORT_TEST_PWD_USER;

-- Roles
DROP ROLE IF EXISTS ORPHAN_ROLE;

-- Network policies
DROP NETWORK POLICY IF EXISTS BAD_OPEN_POLICY;

SELECT 'Snowfort WAF test environment cleaned up.' AS status;
