!set variable_substitution=true;

-- Snowarch Budget Chaos Demo (same as setup_online_failures.sql).
-- Run from repo root: snowarch-admin demo-setup
-- Or from anywhere: snow-architect-audit demo-setup
-- Then: snow-architect-audit scan

USE ROLE ACCOUNTADMIN;

CREATE NETWORK POLICY IF NOT EXISTS BAD_OPEN_POLICY
    ALLOWED_IP_LIST = ('0.0.0.0/0')
    COMMENTS = 'Violates SEC_003';

CREATE WAREHOUSE IF NOT EXISTS BAD_COST_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 3600
    AUTO_RESUME = TRUE
    COMMENT = 'Violates COST_001';

CREATE WAREHOUSE IF NOT EXISTS BAD_MC_WH
    WAREHOUSE_SIZE = 'SMALL'
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = 'STANDARD'
    COMMENT = 'Violates COST_005';

GRANT USAGE ON WAREHOUSE BAD_COST_WH TO ROLE PUBLIC;

CREATE ROLE IF NOT EXISTS ORPHAN_ROLE;

CREATE DATABASE IF NOT EXISTS BAD_PRACTICE_DB;
CREATE SCHEMA IF NOT EXISTS BAD_PRACTICE_DB.PUBLIC;
CREATE TABLE IF NOT EXISTS BAD_PRACTICE_DB.PUBLIC.FRAGILE_TABLE (id INT)
    DATA_RETENTION_TIME_IN_DAYS = 0
    ENABLE_SCHEMA_EVOLUTION = TRUE;

CREATE USER IF NOT EXISTS BAD_ADMIN_USER
    PASSWORD = 'Password123!'
    MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE SYSADMIN TO USER BAD_ADMIN_USER;

CREATE USER IF NOT EXISTS BAD_SVC_USER
    PASSWORD = 'Password123!'
    DEFAULT_ROLE = PUBLIC
    COMMENT = 'Service User';

SELECT 'Demo environment configured. Run: snow-architect-audit scan' AS status;
