-- Snowfort WAF Audit Native App setup script
-- This runs when the app is installed in a consumer account.

CREATE APPLICATION ROLE IF NOT EXISTS SNOWFORT_AUDITOR;

CREATE OR ALTER VERSIONED SCHEMA CORE;
GRANT USAGE ON SCHEMA CORE TO APPLICATION ROLE SNOWFORT_AUDITOR;

CREATE STREAMLIT IF NOT EXISTS CORE.SNOWFORT_AUDIT_APP
    FROM '/src/snowfort_audit/interface'
    MAIN_FILE = 'streamlit_app.py'
    QUERY_WAREHOUSE = REFERENCE('snowflake_warehouse')
    COMMENT = 'Snowfort WAF Audit Dashboard';

GRANT USAGE ON STREAMLIT CORE.SNOWFORT_AUDIT_APP TO APPLICATION ROLE SNOWFORT_AUDITOR;

CREATE OR REPLACE PROCEDURE CORE.CONFIG_REFERENCE_CALLBACK(
    REF_NAME STRING, OPERATION STRING, REF_OR_ALIAS STRING
)
RETURNS STRING
LANGUAGE SQL
AS
$$
    BEGIN
        CASE (OPERATION)
            WHEN 'ADD' THEN SELECT SYSTEM$SET_REFERENCE(:REF_NAME, :REF_OR_ALIAS);
            WHEN 'REMOVE' THEN SELECT SYSTEM$REMOVE_REFERENCE(:REF_NAME);
            WHEN 'CLEAR' THEN SELECT SYSTEM$REMOVE_REFERENCE(:REF_NAME);
        END CASE;
        RETURN 'Done';
    END;
$$;

GRANT USAGE ON PROCEDURE CORE.CONFIG_REFERENCE_CALLBACK(STRING, STRING, STRING)
    TO APPLICATION ROLE SNOWFORT_AUDITOR;
