"""Minimal protocols (vendored)."""

from collections.abc import Generator
from typing import Any, Protocol, runtime_checkable


class TelemetryPort(Protocol):
    """UI/telemetry interface (step, error, info, debug, ask, confirm, handshake). Log level filters info/debug."""

    def step(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...
    def info(self, message: str) -> None: ...
    def warning(self, message: str) -> None: ...
    def debug(self, message: str) -> None: ...
    def ask(self, prompt: str, default: str | None = None) -> str: ...
    def confirm(self, message: str) -> bool: ...
    def handshake(self) -> None: ...
    def set_log_level(self, level: str) -> None: ...


class FileSystemProtocol(Protocol):
    """File system operations."""

    def exists(self, path: str) -> bool: ...
    def read_text(self, path: str, encoding: str = "utf-8") -> str: ...
    def write_text(self, path: str, content: str, encoding: str = "utf-8") -> None: ...
    def join_path(self, *paths: str) -> str: ...
    def walk(self, top: str) -> Generator[tuple[str, list[str], list[str]], None, None]: ...
    def make_dirs(self, path: str, exist_ok: bool = True) -> None: ...
    def get_cwd(self) -> str: ...
    def is_dir(self, path: str) -> bool: ...
    def get_parent(self, path: str) -> str: ...


@runtime_checkable
class SnowflakeCursorProtocol(Protocol):
    """Snowflake cursor interface (DB-API style)."""

    description: Any  # Sequence of column descriptions, or None (e.g. after fetchall())

    def execute(self, command: str, params: Any | None = None) -> Any: ...
    def fetchall(self) -> list[Any]: ...
    def fetchone(self) -> Any: ...
    def close(self) -> bool | None: ...


@runtime_checkable
class SnowflakeQueryProtocol(Protocol):
    """Snowflake connection/query interface."""

    def connect(self) -> None: ...
    def get_cursor(self) -> SnowflakeCursorProtocol: ...
    def get_cursor_for_worker(self, worker_id: int) -> SnowflakeCursorProtocol: ...
    def execute(self, query: str, params: Any | None = None) -> Any: ...
    def execute_ddl(self, builder: Any) -> Any: ...
    def close(self) -> None: ...


class ConfigurationProtocol(Protocol):
    """Environment/configuration access."""

    def get_env(self, key: str, default: str | None = None) -> str | None: ...


class CredentialProtocol(Protocol):
    """Credential storage/retrieval."""

    def get_password(self, account: str, user: str) -> str: ...
    def get_stored_password(self, account: str, user: str) -> str | None: ...
    def get_passcode(self, account: str, user: str) -> str | None: ...
    def clear_credentials(self, account: str, user: str) -> None: ...
